[plugin-info]
## To modify by developper(s) of the plugin
SHORT_PLUGIN_NAME = 'teaching'
package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_teaching'
description = 'Set of base PyMoDAQ plugins including Mock ones for teaching purpose'

author = 'Sébastien Weber'
author-email = 'sebastien.weber@cemes.fr'

[plugin-install]
#packages required for your plugin:
packages-required = ['pymodaq>4.0.0'] #list of required packages within quotes, eg: ["pyvisa", "numpy==1.19.3"] ...
